### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [Sunshine-hami/20200822__kinozal-template#1]
1)
работа содержит невалидный код
![image](https://user-images.githubusercontent.com/8464662/93661777-2eacbc00-fa63-11ea-836f-ca2f2e4ebccf.png)

**Comment by Sunshine-hami** [comment]
оу, даже не знаю, как я могла удалить это. Уже исправила)

**Comment by Alecto** [comment]
и пришлите пожалуйста две ссылочки, они не сохраняются при переписке через
гитхаб

ср, 23 вер. 2020 о 15:46 Sunshine-hami <notifications@github.com> пише:

**Comment by Sunshine-hami** [comment]
https://github.com/Sunshine-hami/20200822__kinozal-template
https://sunshine-hami.github.io/20200822__kinozal-template/

**Comment by Alecto** [comment]
в принципе тоже не сложно поправить
![image](https://user-images.githubusercontent.com/8464662/94052229-509a9b80-fde1-11ea-877f-b3e1816c16dd.png)

**Comment by Alecto** [comment]
еще маленькое замечание там же.
а так - отлично, работа принята.
только пришлите группу и ваше имя, чтобы можно было отметить в журнале.

ср, 23 вер. 2020 о 17:33 Sunshine-hami <notifications@github.com> пише:

**Comment by Sunshine-hami** [comment]
спасибо)
Алена Пасечник вт/чт 17-19

**Comment by Alecto** [comment]
спасибо.
отметил.

ср, 23 вер. 2020 о 21:37 Sunshine-hami <notifications@github.com> пише:
